### ISSUE TITLE
MULTIPLE_RULES_2: src.core.Incoherence: contradiction: expression is already: False

### ISSUE THREAD

**Issue by emilwallner** [emilwallner/Expert-System#1]
B => A
C => A

=B

?A

------

Traceback (most recent call last):
  File "tests.py", line 16, in <module>
    e = parse(line, False)
  File "/Users/ewallner/Desktop/Expert-System/src/parser.py", line 108, in parse
    if (cmd_parse(s, par)):
  File "/Users/ewallner/Desktop/Expert-System/src/parser.py", line 96, in cmd_parse
    facts[letter].set(True)
  File "/Users/ewallner/Desktop/Expert-System/src/core.py", line 20, in set
    raise Incoherence(self)
src.core.Incoherence: contradiction: expression is already: False

**Comment by emilwallner** [comment]
Same for this>>>


B + C => A

D | E => B

B => C



Traceback (most recent call last):
  File "tests.py", line 16, in <module>
    e = parse(line, False)
  File "/Users/ewallner/Desktop/Expert-System/src/parser.py", line 108, in parse
    if (cmd_parse(s, par)):
  File "/Users/ewallner/Desktop/Expert-System/src/parser.py", line 96, in cmd_parse
    facts[letter].set(True)
  File "/Users/ewallner/Desktop/Expert-System/src/core.py", line 20, in set
    raise Incoherence(self)
src.core.Incoherence: contradiction: expression is already: False

**Comment by emilwallner** [comment]
OK
