### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by emilwallner** [emilwallner/Expert-System#2]
B + !C => A

=B

?A

------

testing <_io.TextIOWrapper name='tests/NEGATION_1' mode='r' encoding='UTF-8'>
Traceback (most recent call last):
  File "tests.py", line 16, in <module>
    e = parse(line, False)
  File "/Users/ewallner/Desktop/Expert-System/src/parser.py", line 127, in parse
    raise Exception("dont know {}".format(s[i]))
Exception: dont know !

**Comment by emilwallner** [comment]
ooooook maaaaaaaaybe
