### ISSUE TITLE
Parsing parentheses:

### ISSUE THREAD

**Issue by emilwallner** [emilwallner/Expert-System#3]
(F | G) => E

=

?E

---

testing <_io.TextIOWrapper name='tests/PARENTHESISED_EXPRESSIONS_1' mode='r' encoding='UTF-8'>
Traceback (most recent call last):
  File "tests.py", line 16, in <module>
    e = parse(line, False)
  File "/Users/ewallner/Desktop/Expert-System/src/parser.py", line 120, in parse
    raise Exception("no beginning par")
Exception: no beginning par

**Comment by simdax** [comment]
no more error
